export enum AppState {
    idle,
    recognizing,
    recognize-success,
    recognize-and-predict-success,
    recognize-failed,
    predicting,
    predict-success,
    predict-failed,
    fetching,
    fetch-failed,
}

export enum TerrainType {
    unknown,
    altar,
    block,
    coil,
    crossbow,
    firearm,
}

export enum FetchPhase {
    main-menu,
    mode-select,
    pre-battle,
    in-battle,
    settlement,
    completed,
}

export enum DataSource {
    none,
    adb,
    pc,
    window-capture,
}
